import './globals.css'
import { Karla, Lora } from 'next/font/google'

const karla = Karla({
  subsets: ['latin'],
  variable: '--font-karla',
});
const lora = Lora({
  subsets: ['latin'],
  variable: '--font-lora',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${karla.variable} overflow-x-hidden font-sans ${lora.variable} font-sans`}>{children}</body>
    </html>
  )
}
